# Generated by Django 2.0 on 2018-01-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180105_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
