# Generated by Django 2.0 on 2018-01-30 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180130_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(choices=[('상품5', '상품 5kg'), ('상품10', '상품 10kg'), ('비상품5', '비상품 5kg'), ('비상품10', '비상품 10kg')], max_length=20),
        ),
    ]
