# Generated by Django 2.0 on 2018-01-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180131_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=20),
        ),
    ]
