# Generated by Django 2.0 on 2017-12-13 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0009_auto_20171211_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.ForeignKey(default='71', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
