# Generated by Django 2.0 on 2017-12-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20171213_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='visit',
            new_name='hit',
        ),
    ]
